### ISSUE TITLE
Add WKD support

### ISSUE THREAD

**Issue by Perflyst** [letoams/openpgpkey-milter#5]
Would be nice if this tool supports WKD.
It is not always possible to set an OPENPGPKEY DNS record, and WKD is at least in my opinion much more easier to deploy.

https://wiki.gnupg.org/WKD
https://wiki.gnupg.org/WKDHosting

**Comment by DanWin** [comment]
My fork includes WKD support https://github.com/DanWin/openpgpkey-milter/
See pull request #4

**Comment by Perflyst** [comment]
Oh, nice! Sad that there is no feedback from @letoams on this PR yet..

**Comment by letoams** [comment]
I’ll look at it - not opposed to the idea

**Comment by Perflyst** [comment]
PR was merged, thank you!
